anguage: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kevintruong/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kevintruong/docker-react npm run test -- --coverage
